# Generated by Django 3.2.15 on 2022-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=250)),
                ('t_image', models.ImageField(upload_to='pictures')),
                ('t_description', models.TextField()),
            ],
        ),
    ]
